premiosplatziapp/polls/urls.py
"""
Urls de la app Polls(encuesta)
"""

from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
  path("", views.IndexView.as_view(), name="index"),
  path("<int:pk>/", views.DetailView.as_view(),name="detail"),
  path("<int:pk>/results/", views.ResultView.as_view(),name="results"),
  path("<int:question_id>/vote/", views.vote,name="vote"),
  
  path("prueba/", views.prueba, name="prueba")
  
  
]

premiosplatziapp/premiosplatziapp/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls"))
]

premiosplatziapp/polls/models.py
from django.db import models
from django.utils import timezone

import datetime

"""
Datos de la logica de los modelos de la app polls(encuentas)
"""

class Question(models.Model):
  """Class pregunta del modelo de la tabla questions"""
  question_text = models.CharField(max_length=200)
  pub_date = models.DateTimeField("Date published")
  
  def __str__(self):
    return self.question_text
  
  #Error en los test
  def was_published_recently(self):
    """Si la pregunta fue publicada recientemente"""
    return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)
  
  
  
class Choice(models.Model):
  """Class eleccion del modelo de la tabla choises"""
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0) 
  
  def __str__(self):
    return self.choice_text 

premiosplatziapp/polls/views.py
from django import template
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic


from django.utils import timezone

from .models import Question, Choice


#Las vistas siempre reciben un request http
"""
def index(request):
  latest_question_list = Question.objects.all() #traer todas las preguntas
  
  return render(request, "polls/index.html", {
    "latest_question_list": latest_question_list
  })


#Class Based views - Generoc Visews
#Vistas genéricas para evitar Don Repeat Yourself

def detail(request, question_id):
  #Obtener el detalle
  question = get_object_or_404(Question, pk=question_id) #tare el objeto pero si tiene un error ejecuta automáticamente el 404
  return render(request, "polls/detail.html", {
    "question": question
  })


def results(request, question_id):
  question = get_object_or_404(Question, pk = question_id)
  return render(request, "polls/results.html", {
    "question": question
  })


"""

"""Vistas basadas en clases"""
class IndexView(generic.ListView):
  template_name = "polls/index.html"
  context_object_name = "latest_question_list"
  
  def get_queryset(self):
    """Retorna las ultimas 5 respuestas publicadas"""
    return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]
                                   
  

class DetailView(generic.DetailView):
  model = Question
  template_name= "polls/detail.html"
  
  def get_queryset(self):
    #Excluir cualquier pregunta que no han sido publicadas todavía
    return Question.objects.filter(pub_date__lte=timezone.now())
  

class ResultView(generic.DetailView):
  model = Question
  template_name= "polls/results.html"

def vote(request, question_id):
  """Funcionalidad de elección de respuesta"""
  question = get_object_or_404(Question, pk=question_id)
  try:
    selected_choice = question.choice_set.get(pk=request.POST["choice"])
  except(KeyError, Choice.DoesNotExist):
    return render(request, "polls/detail.html", {
      "question": question,
      "error_message": "No elegiste una respuesta."
    })
  else:
    selected_choice.votes += 1
    selected_choice.save()
    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    


def prueba(request):
  return render(request, 'polls/prueba.html', {
    "texto_prueba": 'Este es el texto de prueba'
  })

premiosplatziapp/polls/templates/polls/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--links-->
  <link rel="stylesheet" href="{% static 'polls/index.css' %}">
  <link rel="stylesheet" href="{% static 'polls/detail.css' %}">
  <!--title-->
  <title>{{question.question_text}}</title>
</head>
<body>
  <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    
    <fieldset>
      <legend>
        <h1>{{question.question_text}}</h1>
      </legend>
    
      {% if error_message %}
        <p class="error_message">{{ error_message }}</p>
      {% endif %}
    
      {% for choice in question.choice_set.all  %}
        <div clas="content">
          <input
            type = "radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{ choice.id }}"
          >
          <label for="choice{{ forloop.counter }}">
            {{  choice.choice_text }}
          </label>
          <br>
        </div>
        
      {% endfor %}
    </fieldset>
    <input type="submit" value="Votar">
    <br>
    <a href="{% url 'polls:index' %}">
      Volver a las preguntas
    </a>
  </form>
</body>
</html>

premiosplatziapp/polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <!--link-->
  <link rel="stylesheet" href="{% static 'polls/reset.css' %}">
  <link rel="stylesheet" href="{% static 'polls/index.css' %}"> 

  <!--title-->
  <title>Index</title>
</head>
<body>

  <header>
    <h1>Premios Platzi App</h1>
  </header>
  <main>
    {% if latest_question_list %}
      <ul> 
        {% for question in latest_question_list %}
        <li>
          <a href="{% url 'polls:detail' question.id %}">
            {{ question.question_text }}
          </a>
        </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No existen encuestas en esta pagina aún.</p>
    {% endif %}
  </main>
  <footer>
    <a href="https://platzi.com">Platzi</a>
    <a href="#">Contacto</a>
    <a href="#">¿Quieres ser profe?</a>
    <a href="#">Politica de privacidad</a>
    <a href="#">Terminos y condiciones</a>
  </footer>
</body>
</html>

premiosplatziapp/polls/templates/polls/prueba.html
{% if  texto_prueba %} 
  <p>
    {{texto_prueba}}
  </p>
{% else %}
  <p>Prueba fallida</p>
{% endif %}

premiosplatziapp/polls/templates/polls/results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--links-->
  <link rel="stylesheet" href="{% static 'polls/index.css' %}">
  <link rel="stylesheet" href="{% static 'polls/results.css' %}">
  
  <!--title-->
  <title>Results {{question.id}}</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
  <ul>
    {% for choice in question.choice_set.all %}
      <li>
        {{ choice.choice_text }} --  {{ choice.votes }} voto{{choice.votes|pluralize}}
      </li>
    {% endfor %}
  </ul>

  <footer>
    <button>
      <a href="{% url 'polls:detail' question.id %}">Votar de nuevo?</a>
    </button>
    <button>
      <a href="{% url 'polls:index' %}">
        Volver a las preguntas
      </a>
    </button>
  </footer>
</body>
</html>